// <auto-generated />
using System;
using DuAnThucTap.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuAnThucTap.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuAnThucTap.Models.BlockLeader", b =>
                {
                    b.Property<int>("BlockLeaderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BlockLeaderID"));

                    b.Property<string>("BlockLeaderName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FK_GradeLevelID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_SchoolYearID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BlockLeaderID");

                    b.HasIndex("FK_GradeLevelID");

                    b.HasIndex("FK_SchoolYearID");

                    b.ToTable("BlockLeaders");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Campus", b =>
                {
                    b.Property<int>("CampusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampusID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPersonEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPersonMobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("CampusID");

                    b.ToTable("Campuses");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassID"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FK_ClassTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_GradeLevelID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_SchoolYearID")
                        .HasColumnType("integer");

                    b.Property<int?>("FK_TeacherID")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClassID");

                    b.HasIndex("FK_ClassTypeID");

                    b.HasIndex("FK_GradeLevelID");

                    b.HasIndex("FK_SchoolYearID");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("DuAnThucTap.Models.ClassType", b =>
                {
                    b.Property<int>("ClassTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClassTypeID"));

                    b.Property<string>("ClassTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClassTypeID");

                    b.ToTable("ClassTypes");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("DuAnThucTap.Models.DepartmentLeader", b =>
                {
                    b.Property<int>("DepartmentLeaderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentLeaderID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentLeaderName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FK_DepartmentID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DepartmentLeaderID");

                    b.HasIndex("FK_DepartmentID");

                    b.ToTable("DepartmentLeaders");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Grade", b =>
                {
                    b.Property<int>("GradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradeID"));

                    b.Property<int?>("FK_ClassTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_GradeTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_SchoolYearID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_SemesterID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_SubjectID")
                        .HasColumnType("integer");

                    b.Property<string>("Instance")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("StudentID")
                        .HasColumnType("integer");

                    b.HasKey("GradeID");

                    b.HasIndex("FK_ClassTypeID");

                    b.HasIndex("FK_GradeTypeID");

                    b.HasIndex("FK_SchoolYearID");

                    b.HasIndex("FK_SemesterID");

                    b.HasIndex("FK_SubjectID");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("DuAnThucTap.Models.GradeLevel", b =>
                {
                    b.Property<int>("GradeLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradeLevelID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FK_SchoolYearID")
                        .HasColumnType("integer");

                    b.Property<int?>("GradeCodeLevel")
                        .HasColumnType("integer");

                    b.Property<string>("GradeLevelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GradeLevelID");

                    b.HasIndex("FK_SchoolYearID");

                    b.ToTable("GradeLevels");
                });

            modelBuilder.Entity("DuAnThucTap.Models.GradeType", b =>
                {
                    b.Property<int>("GradeTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GradeTypeID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GradeTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("MinInstancesSemester1")
                        .HasColumnType("double precision");

                    b.Property<double>("MinInstancesSemester2")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightingFactor")
                        .HasColumnType("double precision");

                    b.HasKey("GradeTypeID");

                    b.ToTable("GradeTypes");
                });

            modelBuilder.Entity("DuAnThucTap.Models.SchoolInformation", b =>
                {
                    b.Property<int>("SchoolInfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolInfoID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EstablishmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaxNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LogoURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrincipalName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PrincipalPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SchoolType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StandardCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrainingModel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WebsiteURL")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("SchoolInfoID");

                    b.ToTable("SchoolInformation");
                });

            modelBuilder.Entity("DuAnThucTap.Models.SchoolYear", b =>
                {
                    b.Property<int>("SchoolYearID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolYearID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndYear")
                        .HasColumnType("integer");

                    b.Property<string>("SchoolYearName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SchoolYearID");

                    b.ToTable("SchoolYears");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Semester", b =>
                {
                    b.Property<int>("SemesterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SemesterID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FK_SchoolYearID")
                        .HasColumnType("integer");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SemesterID");

                    b.HasIndex("FK_SchoolYearID");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultPeriodsSem1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DefaultPeriodsSem2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("FK_SchoolYearID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_SubjectTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubjectID");

                    b.HasIndex("FK_SchoolYearID");

                    b.HasIndex("FK_SubjectTypeID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("DuAnThucTap.Models.SubjectType", b =>
                {
                    b.Property<int>("SubjectTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectTypeID"));

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubjectTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubjectTypeID");

                    b.ToTable("SubjectTypes");
                });

            modelBuilder.Entity("DuAnThucTap.Models.TeachingAssignment", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AssignmentID"));

                    b.Property<int>("FK_ClassID")
                        .HasColumnType("integer");

                    b.Property<int?>("FK_ClassTypeID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_SchoolYearID")
                        .HasColumnType("integer");

                    b.Property<int>("FK_SubjectID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("TeachingEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TeachingStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AssignmentID");

                    b.HasIndex("FK_ClassID");

                    b.HasIndex("FK_ClassTypeID");

                    b.HasIndex("FK_SchoolYearID");

                    b.HasIndex("FK_SubjectID");

                    b.ToTable("TeachingAssignments");
                });

            modelBuilder.Entity("DuAnThucTap.Models.TopicList", b =>
                {
                    b.Property<int>("TopicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicID"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FK_SemesterID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TeachingEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TeachingStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TopicID");

                    b.HasIndex("FK_SemesterID");

                    b.ToTable("TopicLists");
                });

            modelBuilder.Entity("DuAnThucTap.Models.BlockLeader", b =>
                {
                    b.HasOne("DuAnThucTap.Models.GradeLevel", "GradeLevel")
                        .WithMany("BlockLeaders")
                        .HasForeignKey("FK_GradeLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DuAnThucTap.Models.SchoolYear", "SchoolYear")
                        .WithMany("BlockLeaders")
                        .HasForeignKey("FK_SchoolYearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradeLevel");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Class", b =>
                {
                    b.HasOne("DuAnThucTap.Models.ClassType", "ClassType")
                        .WithMany("Classes")
                        .HasForeignKey("FK_ClassTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DuAnThucTap.Models.GradeLevel", "GradeLevel")
                        .WithMany("Classes")
                        .HasForeignKey("FK_GradeLevelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DuAnThucTap.Models.SchoolYear", "SchoolYear")
                        .WithMany("Classes")
                        .HasForeignKey("FK_SchoolYearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassType");

                    b.Navigation("GradeLevel");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("DuAnThucTap.Models.DepartmentLeader", b =>
                {
                    b.HasOne("DuAnThucTap.Models.Department", "Department")
                        .WithMany("DepartmentLeaders")
                        .HasForeignKey("FK_DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Grade", b =>
                {
                    b.HasOne("DuAnThucTap.Models.ClassType", "ClassType")
                        .WithMany("Grades")
                        .HasForeignKey("FK_ClassTypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DuAnThucTap.Models.GradeType", "GradeType")
                        .WithMany("Grades")
                        .HasForeignKey("FK_GradeTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DuAnThucTap.Models.SchoolYear", "SchoolYear")
                        .WithMany("Grades")
                        .HasForeignKey("FK_SchoolYearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DuAnThucTap.Models.Semester", "Semester")
                        .WithMany("Grades")
                        .HasForeignKey("FK_SemesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DuAnThucTap.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("FK_SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassType");

                    b.Navigation("GradeType");

                    b.Navigation("SchoolYear");

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DuAnThucTap.Models.GradeLevel", b =>
                {
                    b.HasOne("DuAnThucTap.Models.SchoolYear", "SchoolYear")
                        .WithMany("GradeLevels")
                        .HasForeignKey("FK_SchoolYearID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Semester", b =>
                {
                    b.HasOne("DuAnThucTap.Models.SchoolYear", "SchoolYear")
                        .WithMany("Semesters")
                        .HasForeignKey("FK_SchoolYearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Subject", b =>
                {
                    b.HasOne("DuAnThucTap.Models.SchoolYear", "SchoolYear")
                        .WithMany("Subjects")
                        .HasForeignKey("FK_SchoolYearID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DuAnThucTap.Models.SubjectType", "SubjectType")
                        .WithMany("Subjects")
                        .HasForeignKey("FK_SubjectTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SchoolYear");

                    b.Navigation("SubjectType");
                });

            modelBuilder.Entity("DuAnThucTap.Models.TeachingAssignment", b =>
                {
                    b.HasOne("DuAnThucTap.Models.Class", "Class")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("FK_ClassID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DuAnThucTap.Models.ClassType", "ClassType")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("FK_ClassTypeID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DuAnThucTap.Models.SchoolYear", "SchoolYear")
                        .WithMany()
                        .HasForeignKey("FK_SchoolYearID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DuAnThucTap.Models.Subject", "Subject")
                        .WithMany("TeachingAssignments")
                        .HasForeignKey("FK_SubjectID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("ClassType");

                    b.Navigation("SchoolYear");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("DuAnThucTap.Models.TopicList", b =>
                {
                    b.HasOne("DuAnThucTap.Models.Semester", "Semester")
                        .WithMany("TopicLists")
                        .HasForeignKey("FK_SemesterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Class", b =>
                {
                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("DuAnThucTap.Models.ClassType", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Grades");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Department", b =>
                {
                    b.Navigation("DepartmentLeaders");
                });

            modelBuilder.Entity("DuAnThucTap.Models.GradeLevel", b =>
                {
                    b.Navigation("BlockLeaders");

                    b.Navigation("Classes");
                });

            modelBuilder.Entity("DuAnThucTap.Models.GradeType", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("DuAnThucTap.Models.SchoolYear", b =>
                {
                    b.Navigation("BlockLeaders");

                    b.Navigation("Classes");

                    b.Navigation("GradeLevels");

                    b.Navigation("Grades");

                    b.Navigation("Semesters");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Semester", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("TopicLists");
                });

            modelBuilder.Entity("DuAnThucTap.Models.Subject", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("TeachingAssignments");
                });

            modelBuilder.Entity("DuAnThucTap.Models.SubjectType", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
